version: "3.2"
services:
  nextjs:
    build: ./next
    container_name: nextjs
    ports:
      - 3000:3000
      - 49153:49153
    volumes:
      - next/:/next/
    command: npm run dev
volumes:
  next: