version: '3'

services:

  python:
    build: ./python
    volumes:
      - ./python:/src
    ports:
    - 5000:5000

  next:
    build: ./next
    volumes:
      - ./next:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
 